site_name: Estudos

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Modo Noturno
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo Claro
  features:
    - navigation.indexes

markdown_extensions:
  - pymdownx.tasklist  # Lista de tarefas
  - pymdownx.emoji  # Emojis
  - pymdownx.mark # Realçado
  - pymdownx.tilde # Tachado
  - pymdownx.highlight # sintax highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.details

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@9
