[tool.pytest.ini_options]
testpaths="tests"
pythonpath="."
addopts=["--strict-markers", "--strict-config"]

[others]
addopts_coverage=["--cov=src", "--cov-report=html"]

[tool.blue]
line-length = 115

[tool.taskipy.tasks]
pre_blue = "echo '\\033[0;35m========================== running blue ==========================\\033[0m'"
blue = "blue ."
pre_isort = "echo '\\033[0;35m========================== running isort =========================\\033[0m'"
isort = "isort ."
lint = "task blue && task isort"

test = "pytest -v"
